### ISSUE TITLE
Arguments -k and -v are no longer supported

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#103]
The latest version of `onto_tool` does not support the optional arguments `-k` and `-v` (or at least I think it's the latest version, since I can't be sure given that `-v` is no longer available). This means that the README is out-of-date, but more importantly, the `-v` should be restored.

**Comment by rjyounes** [comment]
I'm not sure why this is happening, because the `arg_parser` is configured to accept `-v`. I've attached screenshots to show the output of both `onto_tool -h` and `onto_tool -v`.

<img width="1208" alt="Screen Shot 2022-10-05 at 9 16 54 AM" src="https://user-images.githubusercontent.com/1693668/194069975-e360bba3-f673-477a-8b1d-5e32f0f1f8c8.png">
<img width="948" alt="Screen Shot 2022-10-05 at 9 17 45 AM" src="https://user-images.githubusercontent.com/1693668/194069981-406b2129-e788-48f3-8bc5-d7cc0f5c7e50.png">

**Comment by Jamie-SA** [comment]
@rjyounes I am seeing different results than you are.

I reinstalled onto_tool yesterday. This command runs and builds what looks like a proper zip file (ignore my fake version numbers I'm using for testing):
```
onto_tool bundle -v version 11.12.15 bundle.yaml
```
However, this next command runs and leaves a directory called `gistX.x.x_webDownload/` with files that have a `X.x.x` version number, but I do not see a zip/archive file.
```
onto_tool bundle -v X.x.x 11.12.16 bundle.yaml
```

**Comment by Jamie-SA** [comment]
Also, it looks like `-v` is not supposed to return the version number of the onto-tool, but to specify the version number of the release.

**Comment by rjyounes** [comment]
@Jamie-SA `-v` when run without a subcommand should return the version number, with a subcommand it is used to specify a variable replacement.

However, I can no longer reproduce this behavior, so closing the issue.
