### ISSUE TITLE
Additional options to the --defined-by argument

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#105]
The `--defined-by` argument provides two options:

`all`:   every entity that has any properties other than rdf:type will be annotated.
`strict`: only `owl:Class`, `owl:ObjectProperty`, `owl:DatatypeProperty`, `owl:AnnotationProperty` and `owl:Thing` entities will be annotated.

I'm proposing:

(1) Add `owl:NamedIndividual` to `strict`.
(2) Provide a real all option where _every_ entity is annotated. This is to support, say, ontology scaffolding where terms have not been fleshed out. Perhaps current `all` could be renamed `full` or something similar.

**Comment by rjyounes** [comment]
@bpelakh These are straightforward fixes, but I wanted to get your take before submitting a PR. Was there some reason why you excluded `NamedIndividual` to the list of types in `strict`?

**Comment by bpelakh** [comment]
> @bpelakh These are straightforward fixes, but I wanted to get your take before submitting a PR. Was there some reason why you excluded `NamedIndividual` to the list of types in `strict`?

Unfortunately I don't remember the exact cause for the exclusion, but I suspect it had to do with auto generated Protege import stubs

**Comment by rjyounes** [comment]
Fixed in PR #113.
