### ISSUE TITLE
'Dot' not found

### ISSUE THREAD

**Issue by cameronmore** [semanticarts/ontology-toolkit#118]
Hi,

I recently downloaded the toolkit, using pip install onto_tool, and I have run into an error when dunning it:

FileNotFoundError: [WinError 2] "dot" not found in path.

I have checked 'where dot' and windows tells me that no path was found. I tried checking to make sure graphviz was installed, and I ran 'pip install graphviz' but it said I had already done so. I also tried installing pipdot, and that was also already installed.
Maybe this is a problem I'm having on my local machine, maybe its a problem with pathing, but I haven't been able to troubleshoot it elsewhere.
Thank you for your help!

**Comment by pwin** [comment]
Hi Cameron
You need to install Graphviz from https://graphviz.org/ and ensure that the
dot.exe file is in your path.
Hope this helps
Peter

**Comment by cameronmore** [comment]
Peter,
This did help, but I set the bin folder as a user variable and the dot.exe file as a system variable, but dot is still missing
Cameron

**Comment by cameronmore** [comment]
I downloaded GraphViz, set the bin and exe file in my system variables, and the issues sorted themselves out!

**Comment by cameronmore** [comment]
I downloaded GraphViz, set the bin and exe file in my system variables, and the issues sorted themselves out!

**Comment by pwin** [comment]
Sounds good. If you've any notes that might help others please just add
them to this issue, and enjoy using the toolkit
