### ISSUE TITLE
Clean stale test outputs before running graphics tests

### ISSUE THREAD

**Issue by kstudzin** [semanticarts/ontology-toolkit#133]
Currently, when running graphics tests, if you make a change that (incorrectly) leads to no output being generated, the old test file does not get overwritten. This means data from the last good test is still there and the test may falsely pass. If we clean old files before running the tests, this can't happen

**Comment by sa-bpelakh** [comment]
We could use a  `@pytest.fixture(autouse=True, scope="session")` and clean up all old test artifacts before each test runs as long as we standardize the location and naming of said artifacts. Or change it to `module` scope so we can localize cleanup to each `test_*` file.
