### ISSUE TITLE
Functional improvements

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#35]
1. We determined that ontologyIRI is not a real predicate (this was my misunderstanding) so it should not be inserted.
2. I would like rdfs:isDefinedBy to include the version number, as this is our only way to indicate what version of the ontology the term belongs to when it's not in a file (in a triple store, over HTTP). This could be an option, for those who prefer otherwise.
3. It would be nice to have an option to replace ALL X.x.x in text. In a few annotations I have, for example, "Version X.x.x does not..." It would be nice to get that changed automatically. Perhaps it doesn't need a new option but could be thrown in with the version-info option. Is it too dangerous to make the assumption that "X.x.x" is not real text? This is less important, perhaps more of a frill. It's easy enough to write "This version of does not..." instead. You may want to mention in the doc that these changes will not be made.

**Comment by sa-bpelakh** [comment]
1. Sure, that's pretty easy
2. Version numbers in `isDefinedBy` should be optional - if requested, the `versionIRI` object would be used for `isDefinedBy`, right?
3. The full replace is supported in bundle during `copy` or `move`. Is there really a need to build it into the command line utility, especially when there are so many ways of replacing text?

**Comment by rjyounes** [comment]
1. Excellent.
2. yes.
3. Agreed, forget it.

One other thing: regarding -d, some of my files import a number of my other ontology files, making it cumbersome to list each dependency. What about this convention: I list PLACEHOLDER VERSION for each placeholder. Thus:
-d Y.y.y 9.3.0 (for gist)
-d X.x.x 1.0.0 (for my own files)
etc. Then authors would of course use different placeholders for every different substitution they want to make.
