### ISSUE TITLE
Replace X.x.x with version number in release notes, if they exist

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#40]
This will save the release manager from remembering this step in doing the release.

Config file should specify the name and location of the release notes file, if there is one.

Note that X.x.x can occur in multiple places, so it should be a full substitution.

**Comment by sa-bpelakh** [comment]
This is already supported in the toolkit, therefore a gist issue, replicated here https://github.com/semanticarts/gist/issues/359.
