### ISSUE TITLE
Remove Protege-generated artifacts

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#41]
Protege generates stub definitions for, e.g., skos annotations, if that ontology is not imported. `onto_tool` could define an action to remove any definition consisting only of a type assertion. Perhaps there would be an option to specify in the config file which namespaces it applies to; if no specification, it would apply to all namespaces.

**Comment by rjyounes** [comment]
Also remove the `owl:NamedIndividual` and `owl:Thing` assertions that Protege adds to instances.

**Comment by bpelakh** [comment]
Is there really a need to create a specific action for this? A SPARQL transform action in a bundle script will do this just fine. I would be happy to assist on the query, and you could create an alias that would pass the input and output locations as variables. Can actually do this as a pre-checkin hook for git, a richer version of the current formatting hook.

**Comment by rjyounes** [comment]
Sure, I'm happy to use whatever implementation seems best to you. When you say "bundle.script" do you mean `bundle.yaml`? I do want this to run on commit, not just on bundle.

**Comment by rjyounes** [comment]
It turns out Protege adds the stub definitions for good reason: in order to keep the ontology DL compliant. We are actually going to [add these back into gist](https://github.com/semanticarts/gist/issues/934). So this issue can be closed.
