### ISSUE TITLE
Confusing installation documentation

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#72]
I find this line of the installation instructions confusing:

To install the toolkit, run pip install . (not the dot at the end of the command!) from the root directory, which will install the onto_tool command and all its dependencies into your environment.

Aside from the fact that "not" should be "include," this must mean you need to download the files and run the install from the root of that directory. However, all I needed to do is run `pip install onto-tool` from anywhere without downloading any files first.

**Comment by kaspar-p** [comment]
If I'm not mistaken the `pip install .` is required for development on the tool, whereas `pip install onto-tool` is for use? Maybe this should be addressed in the documentation.

**Comment by svirgilgood** [comment]
I created this [pull request](https://github.com/semanticarts/ontology-toolkit/pull/77) to address this issue. Does this update make sense for the issue?
