### ISSUE TITLE
Update Dependency Declarations

### ISSUE THREAD

**Issue by dhurlburtusa** [semanticarts/ontology-toolkit#86]
When I install onto_tool into a fresh python environment, pyshacl is not being installed automatically. I assume this is because it is missing from setup.py.

While adding in pyshacl, double check that both setup.py and requirements.txt have not discrepencies.

**Comment by dhurlburtusa** [comment]
TODO:
- Check if pytest-cov should be included in tests_require in setup.py.
- Check if version specs (e.g. >=) need to match between setup.py install_requires and requirements.txt.

**Comment by dhurlburtusa** [comment]
@bpelakh What do you think about changing requirements.txt to

```
-e .
```
as suggested in https://caremad.io/posts/2013/07/setup-vs-requirement/?

Note: I removed `--index-url https://pypi.python.org/simple/` from the author's example because it was mainly illustrative and I believe it is not necessary since we would be pulling from PyPi anyways.

**Comment by dhurlburtusa** [comment]
@bpelakh According to https://pip.pypa.io/en/latest/reference/build-system/, setup.py is the legacy interface. Should we move to  pyproject.toml?

**Comment by NeilGraham** [comment]
Fixed bug with the following code change: https://github.com/semanticarts/ontology-toolkit/commit/7c4a46069ffd42e8390b558a791370180b03cffb
