### ISSUE TITLE
Ignore Test Generated Files

### ISSUE THREAD

**Issue by dhurlburtusa** [semanticarts/ontology-toolkit#87]
After running pytest, about 26 new files are added to `tests/bundle` and `tests/graphic`. Since these are generated by the tests, they shouldn't be committed to the repository. It would be good to update .gitignore to exclude these. Unfortunately, these generated files are mixed in with several committed files. So it's not as easy as ignoring an entire directory.

**Comment by bpelakh** [comment]
Indeed, tests should be modified to use some (ignorable) output directory.
