### ISSUE TITLE
How to override label that says "Gist Ontology"

### ISSUE THREAD

**Issue by uscholdm** [semanticarts/ontology-toolkit#95]
Currently the .png and .dot files created using the --graphic option have a default label that says: "Gist Ontology" followed by the date. This is inappropriate for non-gist ontologies.  I do not see a way to suppress or change the label. I could not find the text "Gist Ontology" anywhere in the code, which might have been a clue.

I request a feature to alter or suppress the label.

**Comment by bpelakh** [comment]
I would like to direct you to the following two command line options, which could be discovered via `onto_tool graphic --help`:
```
  -v VERSION, --version VERSION
                        Version to place in graphic
  -t TITLE, --title TITLE
                        Title to use for graph. If not supplied, the repo URI will be used if graphing an endpoint, or 'Gist' if graphing local files.
```
I believe they are in the documentation.
